# -*- coding: utf-8 -*-
{
    'name': "LogiSync",
    'summary': 'Odoo Module for LogiSync',
    'description': 'Odoo Module for storing, tracking, and monitoring the logistics of TikTok Shop',
    'sequence': -100,
    'author': "Kelompok 1 K2",
    'category': 'Uncategorized',
    'version': '1.0',
    'depends': ['base'],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'views/order_views.xml',
        'views/shipment_views.xml',
        'views/transaction_views.xml',
        'views/partner_views.xml',
        'views/performance_views.xml',
        'views/staff_views.xml',
        'views/menus.xml',
        'data/seq_logistics_shipment.xml',
        'data/seq_logistics_order.xml',
        'data/seq_logistics_transaction.xml'
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
